# Generated by Django 3.2.7 on 2021-09-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_7app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='discription',
            new_name='description',
        ),
    ]
