# Generated by Django 3.2.7 on 2021-09-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_7app', '0002_rename_discription_place_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
            ],
        ),
    ]
